### use tower
GET http://localhost:8080/tower/fixtures/ed25519_test/ed25519.pk

### use tower dir
GET http://localhost:8080/tower/fixtures

### use self
GET http://localhost:8080/self/fixtures/ed25519_test/ed25519.pk
